export const products = [
  {
    id: "1",
    image: require("../assets/images/dress1.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "Office Wear",
    description: "reversible angora cardigan",
    price: "$120",
  },
  {
    id: "2",
    image: require("../assets/images/dress2.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "Black",
    description: "reversible angora cardigan",
    price: "$120",
  },
  {
    id: "3",
    image: require("../assets/images/dress3.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "Church Wear",
    description: "reversible angora cardigan",
    price: "$120",
  },
  {
    id: "4",
    image: require("../assets/images/dress4.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "Lamerei",
    description: "reversible angora cardigan",
    price: "$120",
  },
  {
    id: "5",
    image: require("../assets/images/dress5.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "21WN",
    description: "reversible angora cardigan",
    price: "$120",
  },
  {
    id: "6",
    image: require("../assets/images/dress6.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "Lopo",
    description: "reversible angora cardigan",
    price: "$120",
  },
  {
    id: "7",
    image: require("../assets/images/dress7.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "21WN",
    description: "reversible angora cardigan",
    price: "$120",
  },
  {
    id: "8",
    image: require("../assets/images/dress1.png"),
    icon: require("../assets/images/add_circle.png"),
    title: "Lopo",
    description: "reversible angora cardigan",
    price: "$120",
  },
];
